stages:
  - build
  #- test
  - deploy

variables:
  NUGET_FEED: "https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/"

cache:
  untracked: true
  paths:
    - /root/.nuget/packages/

build-LIFE-API:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - cd LIFE-API
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-LIFE-API --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-LIFE-API/


build-LIFE-Core:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Core/LIFECoreStarter
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-LIFE-Core --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-LIFE-Core/

build-LIFE-Components:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/LIFE-Components
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-LIFE-Components --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-LIFE-Components/

build-BasicAgents:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Agents/BasicAgents
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-BasicAgents --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-BasicAgents/

build-ESC:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Environments/EnvironmentServiceComponent
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-ESC --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-ESC/

build-GeoGridEnvironment:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Environments/GeoGridEnvironment
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-GeoGridEnvironment --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-GeoGridEnvironment

build-GridEnvironment:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Environments/GridEnvironment
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-GridEnvironment --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-GridEnvironment

build-GeoPotentialField:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Layers/GeoPotentialFieldLayer
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-GeoPotentialFieldLayer --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-GeoPotentialFieldLayer

build-GridPotentialField:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Layers/GridPotentialFieldLayer
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-GridPotentialFieldLayer --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-GridPotentialFieldLayer

build-ObstacleLayer:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Layers/ObstacleLayer
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-ObstacleLayer --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-ObstacleLayer

build-TimeSeriesLayer:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Layers/TimeSeriesLayer
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-TimeSeriesLayer --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-TimeSeriesLayer

build-Utilities:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd LIFE-Components/Utilities
    - dotnet build -c Release
    - dotnet pack -c Release --output $CI_PROJECT_DIR/out-Utilities --version-suffix $CI_PIPELINE_ID
  artifacts:
    expire_in: 120 mins
    paths:
      - out-Utilities

pushAllPackages:
  stage: deploy
  image: frolvlad/alpine-mono
  script:
    - mono .nuget/NuGet.exe push out-LIFE-API/LIFE-API.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-LIFE-Core/LIFE-Core.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-LIFE-Components/LIFE-Components.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-BasicAgents/BasicAgents.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-GeoGridEnvironment/GeoGridEnvironment.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-GridEnvironment/GridEnvironment.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-ESC/EnvironmentServiceComponent.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-GeoPotentialFieldLayer/GeoPotentialFieldLayer.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-GridPotentialFieldLayer/GridPotentialFieldLayer.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-ObstacleLayer/ObstacleLayer.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-TimeSeriesLayer/TimeSeriesLayer.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
    - mono .nuget/NuGet.exe push out-Utilities/Utilities.2.1.0-$CI_PIPELINE_ID.nupkg -ApiKey $PUSH_KEY -Source $PUSH_PATH
