stages:
  - build
  - test
  - deploy


buildAgentManagerService:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - cd 01-Code/LIFEv2
    - dotnet restore .
    - cd 01-Code/LIFEv2/LIFE Services/AgentManagerService
    - dotnet build


testAgentManagerService:
  stage: test
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - cd 01-Code/LIFEv2
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd 01-Code/LIFEv2/LIFE Services/AgentManagerService
    - dotnet test

packAndPushAgentManagerService:
  stage: deploy
  image: artifactory.mars.haw-hamburg.de:5000/mono:4.6.2.16
  script:
    - cd 01-Code/LIFEv2/LIFE Services/AgentManagerService
    - dotnet pack -c Release --version-suffix $CI_PIPELINE_ID
    - mono ../../.nuget/NuGet.exe push ./bin/Release/AgentManagerService.2.0.0-$CI_PIPELINE_ID.nupkg -Source Artifactory
    - rm ./bin/Release/AgentManagerService.2.0.0-$CI_PIPELINE_ID.nupkg

buildASC:
  stage: build
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - cd 01-Code/LIFEv2
    - dotnet restore -s https://artifactory.mars.haw-hamburg.de/artifactory/api/nuget/nuget-virtual/ .
    - cd 01-Code/LIFEv2/T-Components/ASC
    - dotnet build


testASC:
  stage: test
  image: artifactory.mars.haw-hamburg.de:5000/microsoft/dotnet:1.1.0-sdk-projectjson
  script:
    - cd 01-Code/LIFEv2
    - dotnet restore .
    - cd 01-Code/LIFEv2/T-Components/ASC
    - dotnet test

packAndPushASC:
  stage: deploy
  image: artifactory.mars.haw-hamburg.de:5000/mono:4.6.2.16
  script:
    - cd 01-Code/LIFEv2/T-Components/ASC
    - dotnet pack -c Release --version-suffix $CI_PIPELINE_ID
    - mono ../../.nuget/NuGet.exe push ./bin/Release/ASC.2.0.0-$CI_PIPELINE_ID.nupkg -Source Artifactory
    - rm ./bin/Release/ASC.2.0.0-$CI_PIPELINE_ID.nupkg
